//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSK_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTangQuaTheoSL
    {
        public int MaKM { get; set; }
        public int MaMH { get; set; }
        public int MaMH_Tang { get; set; }
        public int SoLuongTang { get; set; }
        public Nullable<bool> TrangThaiPV { get; set; }
    
        public virtual ChiTietGiamGiaTheoSL ChiTietGiamGiaTheoSL { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
