//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSK_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.ChiTietGiamGiaTheoSLs = new HashSet<ChiTietGiamGiaTheoSL>();
            this.ChiTietTangQuaTheoSLs = new HashSet<ChiTietTangQuaTheoSL>();
            this.ChiTietTangQuaTheoSLMHs = new HashSet<ChiTietTangQuaTheoSLMH>();
            this.ChiTietTangQuaTheoTGHDs = new HashSet<ChiTietTangQuaTheoTGHD>();
            this.CTHDs = new HashSet<CTHD>();
            this.LichSuCapNhatMatHangs = new HashSet<LichSuCapNhatMatHang>();
        }
    
        public int MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public decimal DonGia { get; set; }
        public int MaBA { get; set; }
        public int MaDV { get; set; }
        public bool TrangThai { get; set; }
        public int SoHD { get; set; }
        public string ImageMH { get; set; }
        public Nullable<bool> TrangThaiPV { get; set; }
    
        public virtual BuoiAn BuoiAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGiamGiaTheoSL> ChiTietGiamGiaTheoSLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTangQuaTheoSL> ChiTietTangQuaTheoSLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTangQuaTheoSLMH> ChiTietTangQuaTheoSLMHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTangQuaTheoTGHD> ChiTietTangQuaTheoTGHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual DonVi_MatHang DonVi_MatHang { get; set; }
        public virtual HopDong HopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuCapNhatMatHang> LichSuCapNhatMatHangs { get; set; }
    }
}
