//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSK_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLKIOSKEntities : DbContext
    {
        public QLKIOSKEntities()
            : base("name=QLKIOSKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuoiAn> BuoiAns { get; set; }
        public virtual DbSet<ChiTiet_TinhTrangKO> ChiTiet_TinhTrangKO { get; set; }
        public virtual DbSet<ChiTietGiamGiaTheoSL> ChiTietGiamGiaTheoSLs { get; set; }
        public virtual DbSet<ChiTietHopDong> ChiTietHopDongs { get; set; }
        public virtual DbSet<ChiTietNap> ChiTietNaps { get; set; }
        public virtual DbSet<ChiTietQC> ChiTietQCs { get; set; }
        public virtual DbSet<ChiTietTangQuaTheoSL> ChiTietTangQuaTheoSLs { get; set; }
        public virtual DbSet<ChiTietTangQuaTheoSLMH> ChiTietTangQuaTheoSLMHs { get; set; }
        public virtual DbSet<ChiTietTangQuaTheoTGHD> ChiTietTangQuaTheoTGHDs { get; set; }
        public virtual DbSet<ChiTietThueKIOSKQC> ChiTietThueKIOSKQCs { get; set; }
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<CTHD> CTHDs { get; set; }
        public virtual DbSet<DonVi_MatHang> DonVi_MatHang { get; set; }
        public virtual DbSet<DotKhuyenMai> DotKhuyenMais { get; set; }
        public virtual DbSet<HinhThuc_ThanhToan> HinhThuc_ThanhToan { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KIOSK> KIOSKs { get; set; }
        public virtual DbSet<KMTheoSLMH> KMTheoSLMHs { get; set; }
        public virtual DbSet<KMTheoTGHD> KMTheoTGHDs { get; set; }
        public virtual DbSet<LanNap> LanNaps { get; set; }
        public virtual DbSet<LichSu_DangNhap> LichSu_DangNhap { get; set; }
        public virtual DbSet<LichSuCapNhatMatHang> LichSuCapNhatMatHangs { get; set; }
        public virtual DbSet<Loai_TinhTrang_KO> Loai_TinhTrang_KO { get; set; }
        public virtual DbSet<LoaiHopDong> LoaiHopDongs { get; set; }
        public virtual DbSet<LoaiMatHang> LoaiMatHangs { get; set; }
        public virtual DbSet<LoaiNhom> LoaiNhoms { get; set; }
        public virtual DbSet<LoaiTien> LoaiTiens { get; set; }
        public virtual DbSet<MatHang> MatHangs { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<QuangCao> QuangCaos { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<V_KIOSK> V_KIOSK { get; set; }
        public virtual DbSet<V_QuangCao> V_QuangCao { get; set; }
        public virtual DbSet<V_ChiTietQC> V_ChiTietQC { get; set; }
    
        public virtual int sp_CONFIG_DELETE(string variable_name)
        {
            var variable_nameParameter = variable_name != null ?
                new ObjectParameter("variable_name", variable_name) :
                new ObjectParameter("variable_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CONFIG_DELETE", variable_nameParameter);
        }
    
        public virtual int sp_CONFIG_INSERT(string variable_name, string value)
        {
            var variable_nameParameter = variable_name != null ?
                new ObjectParameter("variable_name", variable_name) :
                new ObjectParameter("variable_name", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CONFIG_INSERT", variable_nameParameter, valueParameter);
        }
    
        public virtual int sp_CONFIG_UPDATE(string variable_name, string value)
        {
            var variable_nameParameter = variable_name != null ?
                new ObjectParameter("variable_name", variable_name) :
                new ObjectParameter("variable_name", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CONFIG_UPDATE", variable_nameParameter, valueParameter);
        }
    
        public virtual int sp_KIOSK_DELETE(string maKO)
        {
            var maKOParameter = maKO != null ?
                new ObjectParameter("MaKO", maKO) :
                new ObjectParameter("MaKO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KIOSK_DELETE", maKOParameter);
        }
    
        public virtual int sp_KIOSK_INSERT(string maKO, string tenKO, Nullable<System.DateTime> ngayXD, Nullable<System.DateTime> ngayVH, string diaDiem, string nhietDo, Nullable<bool> trangThaiKO, string imageBanner, string connectStr)
        {
            var maKOParameter = maKO != null ?
                new ObjectParameter("MaKO", maKO) :
                new ObjectParameter("MaKO", typeof(string));
    
            var tenKOParameter = tenKO != null ?
                new ObjectParameter("TenKO", tenKO) :
                new ObjectParameter("TenKO", typeof(string));
    
            var ngayXDParameter = ngayXD.HasValue ?
                new ObjectParameter("NgayXD", ngayXD) :
                new ObjectParameter("NgayXD", typeof(System.DateTime));
    
            var ngayVHParameter = ngayVH.HasValue ?
                new ObjectParameter("NgayVH", ngayVH) :
                new ObjectParameter("NgayVH", typeof(System.DateTime));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("DiaDiem", diaDiem) :
                new ObjectParameter("DiaDiem", typeof(string));
    
            var nhietDoParameter = nhietDo != null ?
                new ObjectParameter("NhietDo", nhietDo) :
                new ObjectParameter("NhietDo", typeof(string));
    
            var trangThaiKOParameter = trangThaiKO.HasValue ?
                new ObjectParameter("TrangThaiKO", trangThaiKO) :
                new ObjectParameter("TrangThaiKO", typeof(bool));
    
            var imageBannerParameter = imageBanner != null ?
                new ObjectParameter("ImageBanner", imageBanner) :
                new ObjectParameter("ImageBanner", typeof(string));
    
            var connectStrParameter = connectStr != null ?
                new ObjectParameter("ConnectStr", connectStr) :
                new ObjectParameter("ConnectStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KIOSK_INSERT", maKOParameter, tenKOParameter, ngayXDParameter, ngayVHParameter, diaDiemParameter, nhietDoParameter, trangThaiKOParameter, imageBannerParameter, connectStrParameter);
        }
    
        public virtual int sp_KIOSK_UPDATE(string maKO, string tenKO, Nullable<System.DateTime> ngayXD, Nullable<System.DateTime> ngayVH, string diaDiem, string nhietDo, Nullable<bool> trangThaiKO, string imageBanner, string connectStr)
        {
            var maKOParameter = maKO != null ?
                new ObjectParameter("MaKO", maKO) :
                new ObjectParameter("MaKO", typeof(string));
    
            var tenKOParameter = tenKO != null ?
                new ObjectParameter("TenKO", tenKO) :
                new ObjectParameter("TenKO", typeof(string));
    
            var ngayXDParameter = ngayXD.HasValue ?
                new ObjectParameter("NgayXD", ngayXD) :
                new ObjectParameter("NgayXD", typeof(System.DateTime));
    
            var ngayVHParameter = ngayVH.HasValue ?
                new ObjectParameter("NgayVH", ngayVH) :
                new ObjectParameter("NgayVH", typeof(System.DateTime));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("DiaDiem", diaDiem) :
                new ObjectParameter("DiaDiem", typeof(string));
    
            var nhietDoParameter = nhietDo != null ?
                new ObjectParameter("NhietDo", nhietDo) :
                new ObjectParameter("NhietDo", typeof(string));
    
            var trangThaiKOParameter = trangThaiKO.HasValue ?
                new ObjectParameter("TrangThaiKO", trangThaiKO) :
                new ObjectParameter("TrangThaiKO", typeof(bool));
    
            var imageBannerParameter = imageBanner != null ?
                new ObjectParameter("ImageBanner", imageBanner) :
                new ObjectParameter("ImageBanner", typeof(string));
    
            var connectStrParameter = connectStr != null ?
                new ObjectParameter("ConnectStr", connectStr) :
                new ObjectParameter("ConnectStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KIOSK_UPDATE", maKOParameter, tenKOParameter, ngayXDParameter, ngayVHParameter, diaDiemParameter, nhietDoParameter, trangThaiKOParameter, imageBannerParameter, connectStrParameter);
        }
    
        public virtual int sp_QuangCao_DELETE(Nullable<int> maQC)
        {
            var maQCParameter = maQC.HasValue ?
                new ObjectParameter("MaQC", maQC) :
                new ObjectParameter("MaQC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_QuangCao_DELETE", maQCParameter);
        }
    
        public virtual int sp_QuangCao_INSERT(string noiDung, string hinhAnh, Nullable<int> thoiLuong)
        {
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var thoiLuongParameter = thoiLuong.HasValue ?
                new ObjectParameter("ThoiLuong", thoiLuong) :
                new ObjectParameter("ThoiLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_QuangCao_INSERT", noiDungParameter, hinhAnhParameter, thoiLuongParameter);
        }
    
        public virtual int sp_QuangCao_UPDATE(Nullable<int> maQC, string noiDung, string hinhAnh, Nullable<int> thoiLuong)
        {
            var maQCParameter = maQC.HasValue ?
                new ObjectParameter("MaQC", maQC) :
                new ObjectParameter("MaQC", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var thoiLuongParameter = thoiLuong.HasValue ?
                new ObjectParameter("ThoiLuong", thoiLuong) :
                new ObjectParameter("ThoiLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_QuangCao_UPDATE", maQCParameter, noiDungParameter, hinhAnhParameter, thoiLuongParameter);
        }
    
        public virtual int sp_ChiTietQC_DELETE(Nullable<int> soHD, string maKO, Nullable<int> maQC)
        {
            var soHDParameter = soHD.HasValue ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(int));
    
            var maKOParameter = maKO != null ?
                new ObjectParameter("MaKO", maKO) :
                new ObjectParameter("MaKO", typeof(string));
    
            var maQCParameter = maQC.HasValue ?
                new ObjectParameter("MaQC", maQC) :
                new ObjectParameter("MaQC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChiTietQC_DELETE", soHDParameter, maKOParameter, maQCParameter);
        }
    
        public virtual int sp_ChiTietQC_INSERT(Nullable<int> soHD, string maKO, Nullable<int> maQC, Nullable<System.DateTime> ngayBDQC, Nullable<System.DateTime> ngayKTQC)
        {
            var soHDParameter = soHD.HasValue ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(int));
    
            var maKOParameter = maKO != null ?
                new ObjectParameter("MaKO", maKO) :
                new ObjectParameter("MaKO", typeof(string));
    
            var maQCParameter = maQC.HasValue ?
                new ObjectParameter("MaQC", maQC) :
                new ObjectParameter("MaQC", typeof(int));
    
            var ngayBDQCParameter = ngayBDQC.HasValue ?
                new ObjectParameter("NgayBDQC", ngayBDQC) :
                new ObjectParameter("NgayBDQC", typeof(System.DateTime));
    
            var ngayKTQCParameter = ngayKTQC.HasValue ?
                new ObjectParameter("NgayKTQC", ngayKTQC) :
                new ObjectParameter("NgayKTQC", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChiTietQC_INSERT", soHDParameter, maKOParameter, maQCParameter, ngayBDQCParameter, ngayKTQCParameter);
        }
    
        public virtual int sp_TaiKhoan_Disable(Nullable<int> maTK)
        {
            var maTKParameter = maTK.HasValue ?
                new ObjectParameter("MaTK", maTK) :
                new ObjectParameter("MaTK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaiKhoan_Disable", maTKParameter);
        }
    
        public virtual int sp_TaiKhoan_Enable(Nullable<int> maTK)
        {
            var maTKParameter = maTK.HasValue ?
                new ObjectParameter("MaTK", maTK) :
                new ObjectParameter("MaTK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaiKhoan_Enable", maTKParameter);
        }
    
        public virtual int sp_TaiKhoan_INSERT(string username, string password, Nullable<bool> trangThai, Nullable<int> maKH, Nullable<int> soHD)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var soHDParameter = soHD.HasValue ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaiKhoan_INSERT", usernameParameter, passwordParameter, trangThaiParameter, maKHParameter, soHDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaKHMoi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaKHMoi");
        }
    
        public virtual int sp_KhachHang_INSERT(string cMND, string tenKH, string diaChi, string email, string sDT)
        {
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KhachHang_INSERT", cMNDParameter, tenKHParameter, diaChiParameter, emailParameter, sDTParameter);
        }
    
        public virtual ObjectResult<checkKH_Result> checkKH(string cmnd)
        {
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<checkKH_Result>("checkKH", cmndParameter);
        }
    
        public virtual int sp_PhanQuyen_INSERT(Nullable<int> maTK, Nullable<int> maCN, Nullable<bool> tinhTrang)
        {
            var maTKParameter = maTK.HasValue ?
                new ObjectParameter("MaTK", maTK) :
                new ObjectParameter("MaTK", typeof(int));
    
            var maCNParameter = maCN.HasValue ?
                new ObjectParameter("MaCN", maCN) :
                new ObjectParameter("MaCN", typeof(int));
    
            var tinhTrangParameter = tinhTrang.HasValue ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PhanQuyen_INSERT", maTKParameter, maCNParameter, tinhTrangParameter);
        }
    
        public virtual int sp_TaiKhoan_ChangePassword(Nullable<int> matk, string oldhashedpassword, string newhashedpassword)
        {
            var matkParameter = matk.HasValue ?
                new ObjectParameter("matk", matk) :
                new ObjectParameter("matk", typeof(int));
    
            var oldhashedpasswordParameter = oldhashedpassword != null ?
                new ObjectParameter("oldhashedpassword", oldhashedpassword) :
                new ObjectParameter("oldhashedpassword", typeof(string));
    
            var newhashedpasswordParameter = newhashedpassword != null ?
                new ObjectParameter("newhashedpassword", newhashedpassword) :
                new ObjectParameter("newhashedpassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaiKhoan_ChangePassword", matkParameter, oldhashedpasswordParameter, newhashedpasswordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ChucNangTheoLoaiNhom(Nullable<int> maln)
        {
            var malnParameter = maln.HasValue ?
                new ObjectParameter("maln", maln) :
                new ObjectParameter("maln", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ChucNangTheoLoaiNhom", malnParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> TKMoi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TKMoi");
        }
    }
}
