//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSK_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuangCao()
        {
            this.ChiTietQCs = new HashSet<ChiTietQC>();
        }
    
        public int MaQC { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public int ThoiLuong { get; set; }
        public Nullable<bool> TrangThaiPV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietQC> ChiTietQCs { get; set; }
    }
}
